import React from 'react';
import { Eye, Heart, ShoppingCart, TrendingUp, Sparkles, ArrowUpRight } from 'lucide-react';

export default function AnalyticsView() {
  const stats = [
    { label: 'Total Reel Views', value: '1,428,900', change: '+24.8%', icon: Eye, color: 'text-purple-400' },
    { label: 'Reel Completion Rate', value: '78.4%', change: '+12.2%', icon: TrendingUp, color: 'text-emerald-400' },
    { label: 'Total Engagement Likes', value: '312,450', change: '+18.6%', icon: Heart, color: 'text-pink-400' },
    { label: 'CTA Conversion Revenue', value: '$42,890', change: '+34.1%', icon: ShoppingCart, color: 'text-amber-400' },
  ];

  const topReels = [
    { title: 'Summer Collection Highlight Reel', views: '482K', ctr: '8.4%', sales: '$18,400' },
    { title: 'Interactive SDK Setup Demo', views: '310K', ctr: '12.1%', sales: '$14,200' },
    { title: 'Product Unboxing Shorts', views: '215K', ctr: '6.9%', sales: '$10,290' },
  ];

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
      
      {/* Header */}
      <div className="text-center max-w-2xl mx-auto mb-10">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-xs font-semibold mb-3">
          <TrendingUp className="w-3.5 h-3.5" /> Real-Time Metrics
        </div>
        <h2 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
          SuperReel <span className="bg-gradient-to-r from-emerald-400 via-teal-400 to-cyan-400 bg-clip-text text-transparent">Analytics Dashboard</span>
        </h2>
        <p className="text-slate-400 text-sm mt-2">
          Track video watch time, interactive engagement, and direct revenue generated by your embedded reels.
        </p>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-10">
        {stats.map((stat, idx) => {
          const Icon = stat.icon;
          return (
            <div key={idx} className="p-6 rounded-3xl bg-slate-900/80 border border-slate-800 backdrop-blur-xl flex flex-col justify-between shadow-lg">
              <div className="flex items-center justify-between mb-4">
                <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">{stat.label}</span>
                <div className={`p-2.5 rounded-2xl bg-slate-950 border border-slate-800 ${stat.color}`}>
                  <Icon className="w-5 h-5" />
                </div>
              </div>

              <div>
                <div className="text-3xl font-extrabold text-white tracking-tight">{stat.value}</div>
                <div className="flex items-center gap-1 text-xs font-semibold text-emerald-400 mt-2">
                  <ArrowUpRight className="w-3.5 h-3.5" /> {stat.change} vs last month
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Top Performing Reels Table */}
      <div className="bg-slate-900/80 border border-slate-800 rounded-3xl p-6 backdrop-blur-xl shadow-xl">
        <h3 className="text-lg font-bold text-white mb-4">Top Performing Video Reels</h3>
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b border-slate-800 text-slate-400 text-xs font-bold uppercase">
                <th className="py-3 px-4">Reel Title</th>
                <th className="py-3 px-4">Views</th>
                <th className="py-3 px-4">CTA Click-Through</th>
                <th className="py-3 px-4">Generated Revenue</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60 text-sm">
              {topReels.map((reel, idx) => (
                <tr key={idx} className="hover:bg-slate-800/30 transition">
                  <td className="py-4 px-4 font-semibold text-white">{reel.title}</td>
                  <td className="py-4 px-4 text-purple-400 font-bold">{reel.views}</td>
                  <td className="py-4 px-4 text-emerald-400 font-bold">{reel.ctr}</td>
                  <td className="py-4 px-4 text-amber-400 font-extrabold">{reel.sales}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

    </div>
  );
}
